apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: microcks-pipeline-beer-catalog
spec:
  tasks:
    - name: microcks-test-beer-catalog
      taskRef:
        name: microcks-test
      params:
        - name: apiNameAndVersion
          value: "Beer Catalog API:0.9"
        - name: testEndpoint
          value: http://beer-catalog-impl-beer-catalog-dev.apps.144.76.24.92.nip.io/api/
        - name: runner
          value: POSTMAN
        - name: microcksURL
          value: http://microcks.apps.144.76.24.92.nip.io/api/
        - name: waitFor
          value: 12sec
        - name: keycloakClientId
          value: microcks-serviceaccount
        - name: keycloakClientSecret
          value: 34a49089-7566-45a0-88a6-112b297fd803
        - name: operationsHeaders
          value: |-
            {
              "globals": [
                {"name": "x-api-key", "values": "my-values"}
              ],
              "GET /beer": [
                {"name": "x-trace-id", "values": "xcvbnsdfghjklm"}
              ]
            }
    - name: echo-hello-world
      taskRef:
        name: echo-hello-world
      runAfter:
        - microcks-test-beer-catalog