apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: microcks-test
spec:
  params:
    - name: apiNameAndVersion
      type: string
      description: "<apiName:apiVersion>: Service to test reference. Exemple: 'Beer Catalog API:0.9'"
      default: "Beer Catalog API:0.9"
    - name: testEndpoint
      type: string
      description: "URL where is deployed implementation to test"
    - name: runner
      type: string
      description: "Test strategy (one of: HTTP, SOAP, SOAP_UI, POSTMAN, OPEN_API_SCHEMA, ASYNC_API_SCHEMA, GRPC_PROTOBUF, GRAPHQL_SCHEMA)"
      default: HTTP
    - name: microcksURL
      type: string
      description: "Microcks instance API endpoint"
    - name: keycloakClientId
      type: string
      description: "Keycloak Realm Service Account ClientId"
      default: microcks-serviceaccount
    - name: keycloakClientSecret
      type: string
      description: "Keycloak Realm Service Account ClientSecret"
      default: 7deb71e8-8c80-4376-95ad-00a399ee3ca1
    - name: waitFor
      type: string
      description: "Time to wait for test to finish (int + one of: milli, sec, min)"
      default: 5sec
    - name: filteredOperations
      type: string
      description: "JSON array of the operations' names to consider during the tests"
      default: ""
    - name: operationsHeaders
      type: string
      description: "JSON that override some operations headers for the tests to launch"
      default: ""
  steps:
    - name: microcks-test
      image: quay.io/microcks/microcks-cli:0.5.5
      command:
        - /usr/bin/bash
      args:
        - '-c'
        - >-
          microcks-cli test '$(params.apiNameAndVersion)' $(params.testEndpoint) $(params.runner) \
            --microcksURL=$(params.microcksURL) --waitFor=$(params.waitFor) \
            --keycloakClientId=$(params.keycloakClientId) --keycloakClientSecret=$(params.keycloakClientSecret) \
            --insecure --filteredOperations='$(params.filteredOperations)' --operationsHeaders='$(params.operationsHeaders)'