apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: microcks-test-customcerts-taskrun-beer-catalog
spec:
  taskRef:
    name: microcks-test-customcerts
  params:
    - name: apiNameAndVersion
      value: "Beer Catalog API:0.9"
    - name: testEndpoint
      value: http://beer-catalog-impl-beer-catalog-dev.apps.144.76.24.92.nip.io/api/
    - name: runner
      value: POSTMAN
    - name: microcksURL
      value: https://microcks-secure.apps.144.76.24.92.nip.io/api/
    - name: waitFor
      value: 12sec
    - name: keycloakClientId
      value: microcks-serviceaccount
    - name: keycloakClientSecret
      value: 34a49089-7566-45a0-88a6-112b297fd803
    - name: operationsHeaders
      value: |-
        {
          "globals": [
            {"name": "x-api-key", "values": "my-values"}
          ],
          "GET /beer": [
            {"name": "x-trace-id", "values": "xcvbnsdfghjklm"}
          ]
        }
    - name: caCertsSecret
      value: microcks-test-customcerts-secret