name: build-verify-package
on: [push]
jobs:
  build-verify-package:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'

      - name: Build Go packages
        run: |
          ./build-binaries.sh github.com/microcks/microcks-cli

      - name: Set environment for branch
        run: |
          set -x
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "IMAGE_TAG=nightly" >> "$GITHUB_ENV"
          elif [[ $GITHUB_REF == "refs/tags/$GITHUB_REF_NAME" ]]; then
            echo "IMAGE_TAG=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
          fi

      - name: Package container image for cli
        if: github.repository_owner == 'microcks'
        run: |
          docker build -f build/Dockerfile -t quay.io/microcks/microcks-cli:$IMAGE_TAG .

      - name: Login and push to Quay.io Registry
        if: github.repository_owner == 'microcks'
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
          docker push quay.io/microcks/microcks-cli:$IMAGE_TAG